// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studentmgt.Model;

#nullable disable

namespace Studentmgt.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230907094600_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Studentmgt.Model.Student", b =>
                {
                    b.Property<string>("strStudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtmUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("strCeatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCourseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStudentMobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strStudentId");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
